import type { PdfTaskLanding } from '@/lib/seo/pdf-task-landings';

export type ImageTask = 'optimize' | 'convert';
export type ImageLocale = 'pt-BR' | 'en' | 'es';

const DATA: Record<ImageTask, Record<ImageLocale, PdfTaskLanding>> = {
  optimize: {
    'pt-BR': { task: 'optimize', locale: 'pt-BR', path: '/comprimir-redimensionar-imagem', eyebrow: 'Resolva Jato · Imagens', title: 'Comprimir e redimensionar imagem online', description: 'Comprima e redimensione imagens JPG, PNG e WEBP com controle de dimensões e qualidade. Processamento local e privado no navegador.', h1: 'Comprimir e redimensionar imagem online', subtitle: 'Reduza o tamanho em KB ou ajuste largura e altura com controle visual de qualidade. A imagem não é enviada ao servidor.', steps: ['Selecione uma imagem JPG, PNG ou WEBP.', 'Defina largura, altura, formato e qualidade.', 'Compare o tamanho original e o resultado.', 'Baixe o arquivo otimizado.'], faqs: [{ q: 'A imagem é enviada para um servidor?', a: 'Não. Decodificação, redimensionamento e compressão acontecem no navegador.' }, { q: 'A transparência é preservada?', a: 'Sim em PNG e WEBP. JPG não suporta transparência e recebe fundo branco.' }, { q: 'A ferramenta aumenta imagens pequenas?', a: 'Somente se você informar dimensões maiores. Para melhor nitidez, recomendamos reduzir ou manter o tamanho original.' }] },
    en: { task: 'optimize', locale: 'en', path: '/en/tools/image-optimizer', eyebrow: 'Resolva Jato · Images', title: 'Compress and resize images online', description: 'Compress and resize JPG, PNG and WEBP images with dimension and quality controls. Private local browser processing.', h1: 'Compress and resize images online', subtitle: 'Reduce file size or change width and height with visual quality controls. Your image is not uploaded.', steps: ['Select a JPG, PNG or WEBP image.', 'Choose dimensions, format and quality.', 'Compare original and output file sizes.', 'Download the optimized image.'], faqs: [{ q: 'Is my image uploaded?', a: 'No. Decoding, resizing and compression happen in your browser.' }, { q: 'Is transparency preserved?', a: 'Yes in PNG and WEBP. JPG does not support transparency and uses a white background.' }, { q: 'Can it enlarge small images?', a: 'Only when you enter larger dimensions. Keeping or reducing dimensions provides better sharpness.' }] },
    es: { task: 'optimize', locale: 'es', path: '/es/tools/image-optimizer', eyebrow: 'Resolva Jato · Imágenes', title: 'Comprimir y redimensionar imágenes online', description: 'Comprime y redimensiona imágenes JPG, PNG y WEBP con controles de tamaño y calidad. Procesamiento local y privado.', h1: 'Comprimir y redimensionar imágenes online', subtitle: 'Reduce el peso o cambia ancho y alto con control visual de calidad. La imagen no se sube al servidor.', steps: ['Selecciona una imagen JPG, PNG o WEBP.', 'Define dimensiones, formato y calidad.', 'Compara el tamaño original y el resultado.', 'Descarga la imagen optimizada.'], faqs: [{ q: '¿La imagen se sube a un servidor?', a: 'No. La decodificación, el cambio de tamaño y la compresión ocurren en el navegador.' }, { q: '¿Se conserva la transparencia?', a: 'Sí en PNG y WEBP. JPG no admite transparencia y utiliza fondo blanco.' }, { q: '¿Puede ampliar imágenes pequeñas?', a: 'Solo si indicas dimensiones mayores. Mantener o reducir el tamaño ofrece mejor nitidez.' }] }
  },
  convert: {
    'pt-BR': { task: 'convert', locale: 'pt-BR', path: '/converter-imagem-online', eyebrow: 'Resolva Jato · Conversor', title: 'Converter JPG, PNG e WEBP online', description: 'Converta imagens entre JPG, PNG, WEBP e PDF no navegador. Ajuste dimensões e qualidade antes de baixar, sem enviar o arquivo.', h1: 'Converter imagem online: JPG, PNG, WEBP e PDF', subtitle: 'Troque o formato, ajuste dimensões e exporte para imagem ou PDF com processamento local.', steps: ['Selecione uma imagem JPG, PNG ou WEBP.', 'Escolha JPG, PNG, WEBP ou PDF.', 'Ajuste dimensões e qualidade quando necessário.', 'Gere e baixe o novo arquivo.'], faqs: [{ q: 'Quais conversões são suportadas?', a: 'JPG, PNG e WEBP podem ser convertidos entre si ou exportados como PDF.' }, { q: 'PNG transparente continua transparente?', a: 'Ao exportar para PNG ou WEBP, sim. Ao exportar para JPG, o fundo fica branco.' }, { q: 'O PDF mantém a resolução?', a: 'O PDF usa as dimensões selecionadas e incorpora a imagem na página sem recorte.' }] },
    en: { task: 'convert', locale: 'en', path: '/en/tools/image-converter', eyebrow: 'Resolva Jato · Converter', title: 'Convert JPG, PNG and WEBP online', description: 'Convert JPG, PNG and WEBP images to another image format or PDF in your browser with no upload.', h1: 'Convert images online: JPG, PNG, WEBP and PDF', subtitle: 'Change format, dimensions and quality, then export an image or PDF with local processing.', steps: ['Select a JPG, PNG or WEBP image.', 'Choose JPG, PNG, WEBP or PDF.', 'Adjust dimensions and quality.', 'Generate and download the new file.'], faqs: [{ q: 'Which conversions are supported?', a: 'JPG, PNG and WEBP can be converted into each other or exported as PDF.' }, { q: 'Does transparent PNG stay transparent?', a: 'Yes when exporting PNG or WEBP. JPG uses a white background.' }, { q: 'Does the PDF keep image resolution?', a: 'The PDF uses your selected dimensions and places the image without cropping.' }] },
    es: { task: 'convert', locale: 'es', path: '/es/tools/image-converter', eyebrow: 'Resolva Jato · Conversor', title: 'Convertir JPG, PNG y WEBP online', description: 'Convierte imágenes JPG, PNG y WEBP a otro formato o PDF en el navegador, sin subir archivos.', h1: 'Convertir imágenes online: JPG, PNG, WEBP y PDF', subtitle: 'Cambia formato, dimensiones y calidad, y exporta como imagen o PDF con procesamiento local.', steps: ['Selecciona una imagen JPG, PNG o WEBP.', 'Elige JPG, PNG, WEBP o PDF.', 'Ajusta dimensiones y calidad.', 'Genera y descarga el archivo nuevo.'], faqs: [{ q: '¿Qué conversiones son compatibles?', a: 'JPG, PNG y WEBP pueden convertirse entre sí o exportarse como PDF.' }, { q: '¿El PNG transparente sigue transparente?', a: 'Sí al exportar PNG o WEBP. JPG utiliza fondo blanco.' }, { q: '¿El PDF mantiene la resolución?', a: 'El PDF utiliza las dimensiones elegidas e incorpora la imagen sin recortarla.' }] }
  }
};

export function getImageTaskLanding(task: ImageTask, locale: ImageLocale) { return DATA[task][locale]; }
