import Link from 'next/link';
import { ArrowRight, Building2, Check, ChevronRight, FileText, Home, Printer, QrCode, ShieldCheck } from 'lucide-react';
import { LandingConversionLink } from '@/components/analytics/landing-conversion-link';
import { TopEnvBanner } from '@/components/layout/top-env-banner';
import { SeoLandingJsonLd } from '@/components/marketing/seo-landing-json-ld';
import { SiteFooter } from '@/components/marketing/site-footer';
import { SiteHeader } from '@/components/marketing/site-header';
import { Button } from '@/components/ui/button';
import type { SeoLandingContent } from '@/lib/seo/landing-content';

export function RentalReceiptLanding({ content }: { content: SeoLandingContent }) {
  const situations = [
    { href: '/recibo-de-aluguel/residencial', icon: Home, title: 'Casa ou apartamento', text: 'Imóvel, competência, locador e inquilino.' },
    { href: '/recibo-de-aluguel/comercial', icon: Building2, title: 'Imóvel comercial', text: 'Sala, loja, razão social e CNPJ quando aplicável.' },
    { href: '/recibo-de-aluguel/pix', icon: QrCode, title: 'Aluguel pago por Pix', text: 'Relacione a transferência ao mês quitado.' }
  ] as const;
  return <>
    <SeoLandingJsonLd content={content} />
    <TopEnvBanner />
    <div className="bg-[#f7f8f5] pt-8"><SiteHeader /><main>
      <nav aria-label="Breadcrumb" className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center gap-1 px-4 py-3 text-xs text-slate-500 sm:px-6"><Link href="/">Início</Link><ChevronRight className="h-3 w-3" /><Link href="/recibos">Recibos</Link><ChevronRight className="h-3 w-3" /><span className="font-semibold text-slate-800">Aluguel</span></div></nav>

      <section className="overflow-hidden border-b border-slate-200"><div className="mx-auto grid max-w-6xl gap-12 px-4 py-12 sm:px-6 sm:py-16 lg:grid-cols-[0.92fr_1.08fr] lg:items-center lg:py-20">
        <div><p className="inline-flex rounded-full border border-emerald-200 bg-white px-3 py-1.5 text-xs font-black uppercase tracking-[0.15em] text-emerald-800">Recibo de aluguel online</p><h1 className="rj-display mt-6 text-[clamp(2.6rem,5.5vw,4.7rem)] font-black leading-[0.96] tracking-[-0.05em] text-slate-950">Um recibo claro para quem paga e para quem recebe.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Preencha locador, inquilino, imóvel e mês de referência. Confira o documento na tela e baixe o PDF pronto para imprimir ou enviar.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="h-[52px] rounded-full bg-emerald-800 px-7 font-extrabold hover:bg-emerald-700"><LandingConversionLink href={content.toolHref} landingPath={content.path} placement="hero_primary">Criar meu recibo grátis <ArrowRight className="h-4 w-4" /></LandingConversionLink></Button><Link href="#exemplo" className="inline-flex h-[52px] items-center justify-center rounded-full px-6 text-sm font-bold text-slate-700 hover:bg-white">Ver exemplo preenchido</Link></div><ul className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-sm text-slate-600">{['PDF pronto para imprimir', 'Valor por extenso', 'Residencial ou comercial'].map((item) => <li key={item} className="flex gap-2"><Check className="h-4 w-4 text-emerald-700" />{item}</li>)}</ul></div>
        <div id="exemplo" className="relative scroll-mt-28"><div className="absolute -inset-8 rounded-full bg-emerald-200/30 blur-3xl" /><article className="relative mx-auto max-w-[520px] rotate-[0.7deg] bg-white p-7 shadow-[0_35px_100px_-35px_rgba(15,23,42,0.45)] ring-1 ring-slate-200 sm:p-10"><div className="flex items-start justify-between gap-6 border-b-4 border-emerald-800 pb-5"><div><p className="text-[10px] font-black uppercase tracking-[0.22em] text-emerald-700">Recibo de aluguel</p><h2 className="mt-2 text-xl font-black">RECIBO Nº 008</h2></div><strong className="text-xl text-emerald-800">R$ 1.850,00</strong></div><p className="mt-7 text-sm leading-7 text-slate-700">Recebi de <strong>Mariana Souza</strong> a quantia de <strong>mil oitocentos e cinquenta reais</strong>, referente ao aluguel residencial do imóvel situado na Rua das Palmeiras, 120, competência agosto de 2026.</p><dl className="mt-6 grid gap-4 rounded-2xl bg-slate-50 p-4 text-xs sm:grid-cols-2"><div><dt className="font-black uppercase tracking-wide text-slate-400">Locador</dt><dd className="mt-1 font-bold">Carlos Almeida</dd></div><div><dt className="font-black uppercase tracking-wide text-slate-400">Inquilina</dt><dd className="mt-1 font-bold">Mariana Souza</dd></div><div><dt className="font-black uppercase tracking-wide text-slate-400">Pagamento</dt><dd className="mt-1 font-bold">Pix</dd></div><div><dt className="font-black uppercase tracking-wide text-slate-400">Data</dt><dd className="mt-1 font-bold">10/08/2026</dd></div></dl><div className="mt-12 border-t border-slate-400 pt-2 text-center text-[11px] text-slate-500">Carlos Almeida · locador / recebedor</div><div className="absolute -left-4 top-24 hidden rounded-xl bg-amber-300 px-3 py-2 text-[10px] font-black uppercase tracking-wide shadow-lg sm:block">valor por extenso</div><div className="absolute -right-5 bottom-28 hidden rounded-xl bg-emerald-800 px-3 py-2 text-[10px] font-black uppercase tracking-wide text-white shadow-lg sm:block">dados organizados</div></article></div>
      </div></section>

      <section className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">Qual é a sua situação?</p><div className="mt-5 grid gap-4 md:grid-cols-3">{situations.map((item) => <Link key={item.href} href={item.href} className="group rounded-[1.6rem] border border-slate-200 p-6 transition hover:-translate-y-1 hover:border-emerald-300 hover:shadow-lg"><item.icon className="h-6 w-6 text-emerald-700" /><h2 className="mt-6 text-xl font-black">{item.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{item.text}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-extrabold text-emerald-800">Usar este modelo <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</div></div></section>

      <section className="border-b border-slate-200"><div className="mx-auto grid max-w-6xl gap-12 px-4 py-16 sm:px-6 sm:py-24 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-sky-700">O que não pode faltar</p><h2 className="rj-display mt-3 text-4xl font-black tracking-[-0.035em]">Cinco informações que transformam um papel em um registro útil.</h2></div><ol className="divide-y divide-slate-200 border-y border-slate-200">{['Quem recebeu e quem pagou', 'Qual imóvel está sendo identificado', 'Mês ou competência do aluguel', 'Valor, data e forma de pagamento', 'Assinatura ou identificação do recebedor'].map((item, index) => <li key={item} className="grid grid-cols-[42px_1fr] gap-3 py-5"><span className="font-black text-emerald-700">0{index + 1}</span><span className="font-bold text-slate-800">{item}</span></li>)}</ol></div></section>

      <section className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-24"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-700">Cada documento tem um papel</p><h2 className="rj-display mt-3 text-4xl font-black tracking-[-0.035em]">Comprovante Pix não conta toda a história.</h2></div><div className="mt-10 grid gap-px overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-200 lg:grid-cols-3">{[{ icon: QrCode, label: 'Comprovante Pix', text: 'Mostra que uma transferência aconteceu entre duas contas.' }, { icon: FileText, label: 'Recibo de aluguel', text: 'Explica qual imóvel, valor e competência foram quitados.' }, { icon: ShieldCheck, label: 'Contrato de aluguel', text: 'Define regras, prazo e responsabilidades da locação.' }].map((item) => <div key={item.label} className="bg-white p-7"><item.icon className="h-6 w-6 text-emerald-700" /><h3 className="mt-6 text-xl font-black">{item.label}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{item.text}</p></div>)}</div><p className="mt-6 text-sm text-slate-600">Veja também o <Link href="/contrato-de-aluguel" className="font-extrabold text-emerald-800 hover:underline">contrato de aluguel</Link> e o <Link href="/recibos/recibo-pagamento-pix" className="font-extrabold text-emerald-800 hover:underline">recibo de pagamento Pix</Link>.</p></div></section>

      <section className="border-b border-slate-200"><div className="mx-auto max-w-4xl px-4 py-16 sm:px-6 sm:py-24"><div className="text-center"><Printer className="mx-auto h-7 w-7 text-emerald-700" /><h2 className="rj-display mt-4 text-4xl font-black tracking-[-0.035em]">Dúvidas antes de emitir</h2></div><div className="mt-10 divide-y divide-slate-200 border-y border-slate-200">{content.faqs.map((item) => <details key={item.q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-extrabold">{item.q}<span className="text-xl font-light text-emerald-700 group-open:rotate-45">+</span></summary><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-600">{item.a}</p></details>)}</div></div></section>

      <section className="bg-emerald-950 text-white"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-8 px-4 py-14 sm:px-6 lg:flex-row lg:items-center"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-300">Pronto para preencher?</p><h2 className="rj-display mt-3 text-3xl font-black sm:text-4xl">Seu recibo pode ficar pronto em poucos minutos.</h2></div><Button asChild size="lg" className="h-[52px] rounded-full bg-amber-300 px-7 font-black text-slate-950 hover:bg-amber-200"><LandingConversionLink href={content.toolHref} landingPath={content.path} placement="footer_primary">Criar recibo de aluguel <ArrowRight className="h-4 w-4" /></LandingConversionLink></Button></div></section>
    </main><SiteFooter /></div>
  </>;
}
