import type { ProfessionLanding } from '@/lib/orcamentos/profession-presets';

export const CYCLE_TWO_PROFESSION_LANDINGS: ProfessionLanding[] = [
  {
    slug: 'limpeza-pos-obra', name: 'Limpeza pós-obra', title: 'Orçamento para limpeza pós-obra por ambiente',
    description: 'Calcule limpeza pós-obra com área, estado do imóvel, equipe, vidros, resíduos, prazo, aprovação e Pix.',
    promise: 'Modelo preparado para apartamentos, casas, lojas e imóveis recém-reformados.',
    preset: { occupation: 'limpeza pós-obra', items: [{ nome: 'Vistoria e preparação' }, { nome: 'Limpeza pós-obra dos ambientes' }, { nome: 'Vidros, equipamentos e descarte' }], observacoes: 'Informe área, quantidade de ambientes, resíduos e estado verificado.\nRemoção de tinta, cimento ou adesivo exige teste prévio na superfície.\nPagamento via Pix conforme as etapas combinadas.' },
    checklist: ['Área e estado do imóvel', 'Superfícies e resíduos', 'Equipe, materiais e descarte'],
    example: { client: 'Cliente: Apartamento 302 — exemplo fictício', items: [{ description: 'Vistoria', detail: 'Apartamento vazio de aproximadamente 72 m²', value: 'R$ 120,00' }, { description: 'Limpeza técnica', detail: 'Pisos, revestimentos, louças e armários externos', value: 'R$ 1.180,00' }, { description: 'Vidros e resíduos', detail: '8 folhas acessíveis e retirada ensacada', value: 'R$ 420,00' }], total: 'R$ 1.720,00', terms: ['Execução estimada: 2 dias', 'Equipe de 3 pessoas', '50% na reserva e saldo na entrega via Pix'] },
    sections: [{ title: 'O estado do imóvel define o escopo', paragraphs: ['Metragem sozinha não mostra o esforço. Registre poeira, respingos, adesivos, quantidade de vidros e acesso.', 'Superfícies delicadas precisam de teste antes de qualquer produto ou raspagem.'] }, { title: 'O que não é limpeza pós-obra', paragraphs: ['Retirada de entulho pesado, trabalho em altura e restauração de superfícies devem ser descritos e precificados separadamente.', 'O orçamento organiza a proposta; requisitos de segurança e descarte devem ser avaliados no local.'] }],
    faqs: [{ q: 'Como calcular limpeza pós-obra?', a: 'Combine área, estado, tipos de superfície, equipe, equipamentos, acesso e descarte; evite usar apenas preço por metro quadrado.' }, { q: 'Limpeza de vidros está inclusa?', a: 'Liste quantidade, altura e acesso. Fachadas e trabalho em altura exigem avaliação específica.' }]
  },
  {
    slug: 'moveis-planejados', name: 'Móveis planejados', title: 'Orçamento para móveis planejados com medidas',
    description: 'Detalhe projeto, módulos, MDF, ferragens, acabamento, instalação, cronograma e pagamento por etapas.',
    promise: 'Modelo preparado para cozinhas, dormitórios, escritórios e painéis sob medida.',
    preset: { occupation: 'móveis planejados', items: [{ nome: 'Projeto, medição e detalhamento' }, { nome: 'Módulos, painéis e acabamento' }, { nome: 'Ferragens, transporte e instalação' }], observacoes: 'Medidas finais dependem de conferência técnica.\nDescreva material, espessura, acabamento, ferragens e itens externos.\nEntrada via Pix para materiais e saldo por etapa.' },
    checklist: ['Ambiente e medidas', 'Módulos e materiais', 'Ferragens, prazo e montagem'],
    example: { client: 'Cliente: Renata Souza — exemplo fictício', items: [{ description: 'Projeto executivo', detail: 'Cozinha linear de 3,20 m com torre', value: 'R$ 680,00' }, { description: 'Módulos', detail: 'MDF 18 mm, acabamento branco e amadeirado', value: 'R$ 8.450,00' }, { description: 'Ferragens e montagem', detail: 'Corrediças telescópicas, dobradiças e instalação', value: 'R$ 2.370,00' }], total: 'R$ 11.500,00', terms: ['Validade: 7 dias', 'Produção: 35 dias úteis após medição', '50% de entrada, 40% antes da entrega e 10% na montagem'] },
    sections: [{ title: 'Do desenho à fabricação', paragraphs: ['Liste cada conjunto, dimensões, divisões internas, material, espessura e acabamento.', 'Eletrodomésticos, pedras, iluminação e pontos elétricos só entram quando expressamente descritos.'] }, { title: 'Mudanças depois da medição', paragraphs: ['A produção deve começar com medidas e desenho aprovados. Mudança posterior pode alterar material, prazo e preço.', 'Registre revisões e marcos de pagamento para reduzir dúvidas.'] }],
    faqs: [{ q: 'O orçamento inclui projeto 3D?', a: 'Declare se ele é uma visualização comercial ou detalhamento executivo e quantas revisões estão incluídas.' }, { q: 'Como comparar ferragens?', a: 'Informe tipo, marca ou linha de referência e recursos como amortecimento, pois eles afetam bastante o valor.' }]
  },
  {
    slug: 'box-de-banheiro', name: 'Box de banheiro', title: 'Orçamento para box de banheiro com instalação',
    description: 'Monte orçamento de box com medidas, vidro, ferragens, acabamento, instalação, prazo e entrada por Pix.',
    promise: 'Modelo preparado para box de correr, abrir e configurações de canto.',
    preset: { occupation: 'instalador de box de banheiro', items: [{ nome: 'Medição técnica do vão' }, { nome: 'Vidro e acabamento do box' }, { nome: 'Kit, transporte e instalação' }], observacoes: 'Confirme medidas, abertura, vidro, espessura e cor das ferragens.\nCorreções de piso, parede ou hidráulica não estão inclusas salvo indicação.\nEntrada via Pix para fabricação.' },
    checklist: ['Vão e abertura conferidos', 'Vidro e ferragens definidos', 'Instalação e vedações'],
    example: { client: 'Cliente: Bruno Azevedo — exemplo fictício', items: [{ description: 'Medição', detail: 'Vão frontal de aproximadamente 1,40 m', value: 'R$ 80,00' }, { description: 'Box', detail: 'Vidro temperado incolor 8 mm, duas folhas', value: 'R$ 1.050,00' }, { description: 'Kit e instalação', detail: 'Alumínio branco, transporte, montagem e vedação', value: 'R$ 390,00' }], total: 'R$ 1.520,00', terms: ['Validade: 7 dias', 'Produção: 10 dias úteis', '50% de entrada via Pix'] },
    sections: [{ title: 'Abertura e ferragens', paragraphs: ['O formato do banheiro determina se o box será frontal, de canto, de abrir ou de correr.', 'Especifique cor do perfil, puxador, roldanas e acabamento para o cliente comparar propostas equivalentes.'] }, { title: 'Conferência antes da fabricação', paragraphs: ['Use medidas enviadas apenas como estimativa. A fabricação deve depender da medição técnica e da avaliação dos pontos de fixação.', 'O profissional deve verificar as condições e requisitos aplicáveis à instalação.'] }],
    faqs: [{ q: 'Qual espessura de vidro usar?', a: 'A especificação depende do sistema e das condições do vão; deve ser confirmada pelo profissional responsável.' }, { q: 'Retirada do box antigo está inclusa?', a: 'Somente se estiver listada, incluindo transporte e descarte.' }]
  },
  {
    slug: 'portao-de-ferro', name: 'Portão de ferro', title: 'Orçamento para portão de ferro sob medida',
    description: 'Detalhe medidas, estrutura, chapas, acabamento, automação, transporte, instalação e Pix por etapa.',
    promise: 'Modelo preparado para portões de correr, abrir, basculantes e grades de acesso.',
    preset: { occupation: 'fabricante de portão de ferro', items: [{ nome: 'Medição e desenho do portão' }, { nome: 'Estrutura, chapas e fabricação' }, { nome: 'Acabamento, transporte e instalação' }], observacoes: 'Informe dimensões, sistema de abertura, perfis, chapas e pintura.\nMotor, elétrica e obra civil somente quando descritos.\nEntrada via Pix para material e saldo após instalação.' },
    checklist: ['Medidas e abertura', 'Estrutura e acabamento', 'Automação e obra civil'],
    example: { client: 'Cliente: Casa Vila Verde — exemplo fictício', items: [{ description: 'Projeto', detail: 'Portão de correr com 3,50 × 2,20 m', value: 'R$ 350,00' }, { description: 'Fabricação', detail: 'Estrutura em metalon e fechamento em chapa', value: 'R$ 5.480,00' }, { description: 'Pintura e instalação', detail: 'Fundo anticorrosivo, esmalte, trilho e montagem', value: 'R$ 1.670,00' }], total: 'R$ 7.500,00', terms: ['Validade: 5 dias', 'Prazo: 20 dias úteis', '40% de entrada via Pix'] },
    sections: [{ title: 'Estrutura e sistema de abertura', paragraphs: ['Informe dimensões, perfis, espessuras, fechamento e se o portão corre, abre ou bascula.', 'Motor, controles, alimentação elétrica e adequações civis devem ser itens próprios.'] }, { title: 'Instalação segura', paragraphs: ['Peso, vento, apoios e pontos de fixação influenciam o projeto e precisam de avaliação no local.', 'Quando houver exigência de projeto ou responsabilidade técnica, consulte profissional habilitado.'] }],
    faqs: [{ q: 'O motor está incluído?', a: 'Somente quando modelo, capacidade, controles, instalação e testes aparecem no escopo.' }, { q: 'Como cobrar pintura?', a: 'Descreva preparação, fundo, acabamento, cor e aplicação antes ou depois da montagem.' }]
  },
  {
    slug: 'identidade-visual', name: 'Identidade visual', title: 'Orçamento de identidade visual com entregáveis',
    description: 'Defina estratégia, logotipo, sistema visual, aplicações, revisões, arquivos, prazo e entrada por Pix.',
    promise: 'Modelo preparado para identidade visual básica ou completa de pequenos negócios.',
    preset: { occupation: 'designer de identidade visual', items: [{ nome: 'Briefing, pesquisa e estratégia visual' }, { nome: 'Logotipo e sistema de identidade' }, { nome: 'Aplicações, manual e arquivos finais' }], observacoes: 'Informe entregáveis, propostas e rodadas de revisão.\nNaming, registro de marca, impressão e licenças não estão inclusos salvo indicação.\n50% de entrada via Pix e saldo antes dos arquivos finais.' },
    checklist: ['Escopo estratégico', 'Aplicações e arquivos', 'Revisões e direitos de uso'],
    example: { client: 'Cliente: Estúdio Raiz — exemplo fictício', items: [{ description: 'Estratégia visual', detail: 'Briefing, referências e direção criativa', value: 'R$ 900,00' }, { description: 'Sistema de marca', detail: 'Logotipo, variações, cores e tipografia', value: 'R$ 2.600,00' }, { description: 'Aplicações e manual', detail: 'Cartão digital, avatar, capa e guia de uso', value: 'R$ 1.300,00' }], total: 'R$ 4.800,00', terms: ['Prazo: 25 dias úteis', 'Até 2 rodadas por etapa', '50% de entrada via Pix'] },
    sections: [{ title: 'Identidade é mais que logotipo', paragraphs: ['Diferencie símbolo, assinaturas, paleta, tipografia, elementos gráficos, aplicações e manual.', 'Liste os formatos entregues e as fontes ou imagens que dependem de licença.'] }, { title: 'Direitos e registro', paragraphs: ['Defina quando os direitos de uso dos elementos originais são transferidos.', 'Pesquisa visual não garante registro ou exclusividade jurídica da marca; esse serviço deve ser qualificado separadamente.'] }],
    faqs: [{ q: 'Qual a diferença para criação de logotipo?', a: 'A identidade visual costuma incluir um sistema mais amplo, com regras, elementos e aplicações além do logo.' }, { q: 'Arquivos editáveis estão inclusos?', a: 'Declare formatos e condições de entrega; fontes e ativos licenciados podem ter restrições.' }]
  },
  {
    slug: 'fotografia-de-evento', name: 'Fotografia de evento', title: 'Orçamento para fotografia de evento por hora',
    description: 'Apresente cobertura, equipe, horas, tratamento, entrega, deslocamento, adicionais, reserva e Pix.',
    promise: 'Modelo preparado para aniversários, eventos corporativos, formaturas e confraternizações.',
    preset: { occupation: 'fotógrafo de eventos', items: [{ nome: 'Cobertura fotográfica por período' }, { nome: 'Equipe e deslocamento' }, { nome: 'Seleção, tratamento e galeria' }], observacoes: 'Informe data, endereço, duração, equipe e momentos prioritários.\nHoras extras, impressões e entrega expressa devem ser cobradas à parte.\nReserva da data mediante entrada via Pix.' },
    checklist: ['Data, local e duração', 'Equipe e momentos-chave', 'Entrega e horas extras'],
    example: { client: 'Cliente: Empresa Horizonte — exemplo fictício', items: [{ description: 'Cobertura', detail: 'Evento corporativo por 4 horas', value: 'R$ 1.600,00' }, { description: 'Deslocamento', detail: 'Equipe de 1 fotógrafo na região urbana', value: 'R$ 180,00' }, { description: 'Entrega', detail: 'Seleção, tratamento e galeria em alta resolução', value: 'R$ 620,00' }], total: 'R$ 2.400,00', terms: ['Reserva de 30% via Pix', 'Hora adicional: R$ 350', 'Entrega em até 12 dias úteis'] },
    sections: [{ title: 'Cobertura delimitada', paragraphs: ['Registre horário de início e fim, locais, equipe e momentos que não podem faltar.', 'Explique a estimativa de fotos, critérios de seleção e nível de tratamento.'] }, { title: 'Uso das imagens', paragraphs: ['Autorização para divulgação ou portfólio deve ser tratada expressamente com o contratante e, quando necessário, participantes.', 'Não presuma consentimento apenas porque o orçamento foi aprovado.'] }],
    faqs: [{ q: 'Quantas fotos devo prometer?', a: 'Use uma estimativa coerente com duração e tipo de evento, explicando seleção e descarte técnico.' }, { q: 'Como cobrar entrega urgente?', a: 'Crie um adicional com prazo específico e confirme disponibilidade antes de oferecer.' }]
  },
  {
    slug: 'gesseiro', name: 'Gesseiro', title: 'Orçamento para gesseiro por metro e acabamento',
    description: 'Organize forro, sancas, drywall, reparos, materiais, recortes, pintura, prazo e pagamento por etapa.',
    promise: 'Modelo preparado para forros, paredes, sancas, nichos e reparos em gesso.',
    preset: { occupation: 'gesseiro', items: [{ nome: 'Proteção e preparação do local' }, { nome: 'Estrutura e execução em gesso' }, { nome: 'Recortes, acabamento e limpeza' }], observacoes: 'Informe metragem, pé-direito, desenho, recortes e acabamento.\nElétrica, pintura e reforços somente quando descritos.\nEntrada para materiais e saldo via Pix na entrega.' },
    checklist: ['Metragem e desenho', 'Estrutura e recortes', 'Acabamento e serviços externos'],
    example: { client: 'Cliente: Sala Comercial 12 — exemplo fictício', items: [{ description: 'Preparação', detail: 'Proteção do piso e marcação de 38 m²', value: 'R$ 380,00' }, { description: 'Forro drywall', detail: 'Estrutura, chapas e instalação', value: 'R$ 3.420,00' }, { description: 'Acabamento', detail: 'Tratamento de juntas e 12 recortes de iluminação', value: 'R$ 780,00' }], total: 'R$ 4.580,00', terms: ['Prazo: 6 dias úteis', 'Pintura não inclusa', '40% de entrada via Pix'] },
    sections: [{ title: 'Metragem não é o único fator', paragraphs: ['Pé-direito, curvas, sancas, nichos, recortes e acesso alteram material e produtividade.', 'Identifique se o acabamento fica pronto para pintura e quem fará instalações embutidas.'] }, { title: 'Coordenação com outros serviços', paragraphs: ['Elétrica, climatização e pintura devem ter sequência e responsabilidades definidas.', 'Estruturas ou situações especiais podem exigir avaliação técnica apropriada.'] }],
    faqs: [{ q: 'Pintura está incluída?', a: 'Não presuma. Declare se o serviço termina no tratamento de juntas, selador ou pintura final.' }, { q: 'Como cobrar recortes de iluminação?', a: 'Liste a quantidade e o tipo; rasgos, reforços ou sancas devem aparecer separadamente.' }]
  },
  {
    slug: 'tecnico-de-informatica', name: 'Técnico de informática', title: 'Orçamento para técnico de informática',
    description: 'Separe diagnóstico, configuração, peças, backup, atendimento remoto ou presencial, prazo e Pix.',
    promise: 'Modelo preparado para computadores, notebooks, redes e suporte a pequenos negócios.',
    preset: { occupation: 'técnico de informática', items: [{ nome: 'Diagnóstico do equipamento' }, { nome: 'Serviço de manutenção ou configuração' }, { nome: 'Peças, backup e deslocamento' }], observacoes: 'Identifique equipamento, sintomas e testes autorizados.\nPeças, recuperação de dados e licenças dependem de aprovação específica.\nPagamento via Pix após a validação do serviço.' },
    checklist: ['Equipamento e sintoma', 'Serviço e peças separados', 'Dados, licenças e garantia'],
    example: { client: 'Cliente: Papelaria Central — exemplo fictício', items: [{ description: 'Diagnóstico', detail: 'Notebook com lentidão e falhas de inicialização', value: 'R$ 120,00' }, { description: 'Manutenção', detail: 'Limpeza interna, sistema e atualização de drivers', value: 'R$ 280,00' }, { description: 'Armazenamento', detail: 'SSD 480 GB e clonagem do sistema', value: 'R$ 390,00' }], total: 'R$ 790,00', terms: ['Prazo estimado: 2 dias úteis', 'Backup confirmado antes da intervenção', 'Pix após teste com o cliente'] },
    sections: [{ title: 'Diagnóstico antes da troca', paragraphs: ['Descreva sintomas, testes e diferença entre mão de obra e componentes.', 'Nenhuma peça ou serviço adicional deve ser executado sem apresentar a nova condição ao cliente.'] }, { title: 'Dados e licenças', paragraphs: ['Combine responsabilidade por backup, credenciais e tratamento dos dados antes da intervenção.', 'Software deve usar licenças válidas; recuperação de dados não deve ser prometida como resultado garantido.'] }],
    faqs: [{ q: 'Posso cobrar diagnóstico?', a: 'Sim. Informe o valor e se haverá abatimento quando o reparo for aprovado.' }, { q: 'Como tratar risco de perda de dados?', a: 'Registre a situação do equipamento, ofereça backup quando viável e explique limites antes do serviço.' }]
  }
];
