import type { ProfessionLanding } from '@/lib/orcamentos/profession-presets';

export const CYCLE_THREE_PROFESSION_LANDINGS: ProfessionLanding[] = [
  {
    slug: 'azulejista', name: 'Azulejista', title: 'Orçamento para azulejista por metro quadrado',
    description: 'Detalhe preparação, metragem, paginação, assentamento, recortes, rejunte, materiais, prazo e Pix.',
    promise: 'Modelo preparado para pisos, paredes, cozinhas, banheiros e fachadas acessíveis.',
    preset: { occupation: 'azulejista', items: [{ nome: 'Preparação e regularização da base' }, { nome: 'Assentamento de pisos ou revestimentos' }, { nome: 'Recortes, rejunte e acabamento' }], observacoes: 'Informe área, formato das peças, paginação e estado da base.\nImpermeabilização, demolição e contrapiso somente quando descritos.\nEntrada para materiais e saldo via Pix por etapa.' },
    checklist: ['Metragem e formato das peças', 'Base e paginação', 'Recortes, rejunte e limpeza'],
    example: { client: 'Cliente: Banheiro suíte — exemplo fictício', items: [{ description: 'Preparação', detail: 'Regularização localizada de 18 m²', value: 'R$ 540,00' }, { description: 'Assentamento', detail: 'Porcelanato 90 × 90 cm em piso e parede', value: 'R$ 2.160,00' }, { description: 'Acabamento', detail: 'Recortes, nicho e rejunte', value: 'R$ 680,00' }], total: 'R$ 3.380,00', terms: ['Prazo: 6 dias úteis', 'Revestimentos fornecidos pelo cliente', '30% na entrada e saldo por etapa via Pix'] },
    sections: [{ title: 'Peça, paginação e base', paragraphs: ['Preço por metro muda conforme formato, desenho, quantidade de recortes e condição da superfície.', 'Registre quem fornece argamassa, espaçadores, rejunte e revestimentos.'] }, { title: 'Serviços anteriores ao assentamento', paragraphs: ['Demolição, descarte, impermeabilização e regularização precisam aparecer como etapas próprias.', 'Condições ocultas devem gerar proposta complementar antes da execução.'] }],
    faqs: [{ q: 'Como cobrar porcelanato grande?', a: 'Considere peso, nivelamento, equipamento, dupla colagem e recortes; não use automaticamente o preço de peças pequenas.' }, { q: 'Impermeabilização está inclusa?', a: 'Somente se estiver descrita com área, sistema e condições de aplicação.' }]
  },
  {
    slug: 'montador-de-moveis', name: 'Montador de móveis', title: 'Orçamento para montador de móveis por item',
    description: 'Liste móveis, quantidade, complexidade, fixações, desmontagem, deslocamento, prazo e pagamento por Pix.',
    promise: 'Modelo preparado para móveis novos, desmontagem, remontagem e pequenos ajustes.',
    preset: { occupation: 'montador de móveis', items: [{ nome: 'Montagem dos móveis listados' }, { nome: 'Fixações e ajustes' }, { nome: 'Deslocamento ou desmontagem' }], observacoes: 'Identifique cada móvel, marca, modelo, dimensões e estado das peças.\nFixação em parede depende da superfície e das condições encontradas.\nPagamento via Pix após conferência.' },
    checklist: ['Móveis e quantidades', 'Marca, modelo e estado', 'Fixações e deslocamento'],
    example: { client: 'Cliente: Juliana Martins — exemplo fictício', items: [{ description: 'Guarda-roupa', detail: '6 portas, 4 gavetas, produto novo', value: 'R$ 320,00' }, { description: 'Painel de TV', detail: 'Montagem e fixação em parede de alvenaria', value: 'R$ 180,00' }, { description: 'Deslocamento', detail: 'Atendimento dentro da área urbana', value: 'R$ 60,00' }], total: 'R$ 560,00', terms: ['Execução estimada: 1 dia', 'Peças faltantes serão informadas', 'Pix após conferência do cliente'] },
    sections: [{ title: 'Um item por móvel', paragraphs: ['Nomeie cada móvel e registre tamanho, quantidade de portas e gavetas e se está novo ou usado.', 'Desmontagem, transporte, recorte e adaptação devem ser cobrados separadamente.'] }, { title: 'Fixação e peças faltantes', paragraphs: ['A parede e a infraestrutura precisam ser verificadas antes de fixar itens suspensos.', 'Se houver peça danificada ou ausente, documente e aguarde decisão do cliente.'] }],
    faqs: [{ q: 'Como cobrar móvel sem manual?', a: 'Considere tempo adicional e deixe claro que a montagem depende da identificação correta das peças.' }, { q: 'Desmontagem inclui transporte?', a: 'Não necessariamente. Liste desmontagem, embalagem, transporte e remontagem como serviços distintos.' }]
  },
  {
    slug: 'chaveiro', name: 'Chaveiro', title: 'Orçamento para chaveiro com peças e atendimento',
    description: 'Organize visita, abertura, troca de segredo, cópias, fechadura, deslocamento, urgência e Pix.',
    promise: 'Modelo preparado para residências, comércios, veículos e atendimentos emergenciais autorizados.',
    preset: { occupation: 'chaveiro', items: [{ nome: 'Deslocamento e avaliação' }, { nome: 'Abertura ou serviço de chave' }, { nome: 'Fechadura, cilindro ou peças' }], observacoes: 'Identifique local, tipo de fechadura e urgência.\nO atendimento depende de comprovação de autorização sobre o imóvel, veículo ou bem.\nPagamento via Pix na conclusão.' },
    checklist: ['Local e tipo de fechadura', 'Urgência e deslocamento', 'Autorização e peças'],
    example: { client: 'Cliente: Comércio Avenida — exemplo fictício', items: [{ description: 'Deslocamento', detail: 'Atendimento comercial no período diurno', value: 'R$ 80,00' }, { description: 'Troca de segredo', detail: 'Cilindro de porta de entrada', value: 'R$ 140,00' }, { description: 'Peças', detail: 'Cilindro compatível e três chaves', value: 'R$ 170,00' }], total: 'R$ 390,00', terms: ['Atendimento no mesmo dia', 'Sujeito à comprovação de autorização', 'Pix após teste das chaves'] },
    sections: [{ title: 'Urgência e deslocamento', paragraphs: ['Informe distância, horário e adicional de emergência antes de sair para o atendimento.', 'Separe mão de obra de fechaduras, cilindros, chaves e controles.'] }, { title: 'Autorização do atendimento', paragraphs: ['Antes de abrir ou alterar acesso, verifique se a pessoa está autorizada a solicitar o serviço.', 'O orçamento não substitui procedimentos de identificação e segurança do profissional.'] }],
    faqs: [{ q: 'Posso cobrar adicional noturno?', a: 'Sim. Informe o valor ou critério antes do deslocamento e registre-o no orçamento.' }, { q: 'A abertura pode danificar a fechadura?', a: 'Explique o método previsto e possíveis limitações após avaliar o mecanismo; evite garantia sem inspeção.' }]
  },
  {
    slug: 'dedetizacao', name: 'Dedetização', title: 'Orçamento para dedetização por área e praga',
    description: 'Detalhe área, praga-alvo, método, preparação, retorno, prazo, cuidados, responsável e pagamento por Pix.',
    promise: 'Modelo preparado para controle de pragas em residências e pequenos estabelecimentos.',
    preset: { occupation: 'controle de pragas', items: [{ nome: 'Inspeção e identificação da ocorrência' }, { nome: 'Aplicação de controle de pragas' }, { nome: 'Retorno técnico e orientações' }], observacoes: 'Informe área, praga-alvo, método e preparação necessária.\nProdutos, intervalo de reentrada e cuidados devem seguir orientação da empresa responsável.\nPagamento via Pix conforme combinado.' },
    checklist: ['Área e praga identificadas', 'Método e preparação', 'Reentrada, retorno e responsável'],
    example: { client: 'Cliente: Restaurante Exemplo — exemplo fictício', items: [{ description: 'Inspeção', detail: 'Cozinha, estoque e área de atendimento — 140 m²', value: 'R$ 180,00' }, { description: 'Tratamento', detail: 'Controle direcionado à ocorrência identificada', value: 'R$ 780,00' }, { description: 'Retorno', detail: 'Reinspeção programada e orientações preventivas', value: 'R$ 220,00' }], total: 'R$ 1.180,00', terms: ['Execução fora do horário de operação', 'Preparação conforme orientação técnica', 'Pix na execução'] },
    sections: [{ title: 'Diagnóstico antes do tratamento', paragraphs: ['Área, espécie-alvo, nível de ocorrência e condições do local determinam método e frequência.', 'Evite oferecer uma aplicação genérica sem inspeção e instruções de preparação.'] }, { title: 'Segurança e regularidade', paragraphs: ['Produtos e procedimentos devem ser definidos por empresa e responsáveis devidamente qualificados conforme as exigências aplicáveis.', 'O modelo comercial não substitui documentação técnica, instruções de segurança ou licenças.'] }],
    faqs: [{ q: 'Posso garantir eliminação total?', a: 'Não faça promessa absoluta. Explique fatores do ambiente, prevenção, monitoramento e condições do retorno.' }, { q: 'Quanto tempo o local fica vazio?', a: 'O intervalo depende do método e produto; use somente a orientação técnica específica do tratamento.' }]
  },
  {
    slug: 'mudanca-residencial', name: 'Mudança residencial', title: 'Orçamento para mudança residencial detalhado',
    description: 'Liste origem, destino, volume, equipe, veículo, embalagem, desmontagem, acesso, seguro, prazo e Pix.',
    promise: 'Modelo preparado para mudanças locais de apartamentos e casas.',
    preset: { occupation: 'mudança residencial', items: [{ nome: 'Equipe e veículo de mudança' }, { nome: 'Embalagem e proteção' }, { nome: 'Desmontagem, montagem e adicionais' }], observacoes: 'Informe endereços, inventário, acessos, datas e restrições de condomínio.\nIçamento, armazenamento e itens especiais somente quando descritos.\nSinal via Pix para reserva e saldo na conclusão.' },
    checklist: ['Origem, destino e data', 'Inventário e volume', 'Acessos, embalagem e adicionais'],
    example: { client: 'Cliente: Família Oliveira — exemplo fictício', items: [{ description: 'Transporte', detail: 'Caminhão e equipe de 3 pessoas em trajeto de 18 km', value: 'R$ 1.650,00' }, { description: 'Embalagem', detail: 'Proteção de móveis e 35 caixas', value: 'R$ 620,00' }, { description: 'Montagem', detail: 'Desmontagem e remontagem de 3 móveis', value: 'R$ 480,00' }], total: 'R$ 2.750,00', terms: ['Reserva de 30% via Pix', 'Janela estimada de 8 horas', 'Içamento não incluso'] },
    sections: [{ title: 'Inventário e acesso', paragraphs: ['Relacione móveis, eletrodomésticos, caixas e itens frágeis, além de escadas, elevadores e distância até o veículo.', 'Regras e horários dos condomínios devem ser confirmados pelos envolvidos.'] }, { title: 'Itens especiais', paragraphs: ['Cofres, pianos, obras, içamento e armazenamento precisam de avaliação e preço próprios.', 'Defina proteção, conferência e condições de responsabilidade sem usar garantias absolutas.'] }],
    faqs: [{ q: 'Como estimar o volume?', a: 'Use inventário, fotos e vistoria; quantidade de cômodos é apenas uma referência inicial.' }, { q: 'Caixas estão incluídas?', a: 'Informe quantidade, tipo, entrega, montagem e recolhimento, se houver.' }]
  },
  {
    slug: 'energia-solar', name: 'Energia solar', title: 'Orçamento de energia solar com premissas técnicas',
    description: 'Organize levantamento, projeto, equipamentos, instalação, homologação, garantias, prazo e condições de pagamento.',
    promise: 'Modelo comercial para sistemas fotovoltaicos, condicionado à análise técnica e regulatória aplicável.',
    preset: { occupation: 'integrador de energia solar', items: [{ nome: 'Levantamento e projeto do sistema' }, { nome: 'Módulos, inversor e estruturas' }, { nome: 'Instalação, testes e processo de conexão' }], observacoes: 'Informe consumo analisado, premissas de geração, equipamentos e condições do telhado.\nEstimativas dependem de irradiação, sombreamento, consumo, tarifas e regras vigentes.\nProjeto e execução devem ter responsáveis habilitados quando exigidos.' },
    checklist: ['Consumo e premissas', 'Equipamentos e garantias', 'Projeto, instalação e conexão'],
    example: { client: 'Cliente: Residência Solar — exemplo fictício', items: [{ description: 'Engenharia', detail: 'Levantamento, dimensionamento preliminar e projeto', value: 'R$ 2.400,00' }, { description: 'Equipamentos', detail: 'Sistema ilustrativo de 5,5 kWp, sujeito à vistoria', value: 'R$ 18.900,00' }, { description: 'Instalação e conexão', detail: 'Estrutura, proteções, montagem, testes e documentação', value: 'R$ 5.200,00' }], total: 'R$ 26.500,00', terms: ['Valor demonstrativo sujeito à vistoria', 'Cronograma depende de análise e disponibilidade', 'Pagamento por marcos definidos em contrato'] },
    sections: [{ title: 'Premissas verificáveis', paragraphs: ['Registre histórico de consumo, orientação, inclinação, sombreamento, perdas consideradas e características do telhado.', 'Produção e economia são estimativas, não garantias absolutas; tarifas, clima, consumo e regras podem mudar.'] }, { title: 'Responsabilidade técnica e conexão', paragraphs: ['Projeto, instalação, proteção e documentação devem seguir os requisitos aplicáveis e contar com profissionais habilitados quando exigido.', 'O gerador organiza a proposta comercial e não substitui vistoria, projeto, contrato ou análise da distribuidora.'] }],
    faqs: [{ q: 'Posso prometer zerar a conta de luz?', a: 'Não. Apresente simulações qualificadas e explique custos mínimos, variação de consumo, clima, tarifas e regras aplicáveis.' }, { q: 'Homologação está inclusa?', a: 'Liste exatamente quais documentos e etapas serão conduzidos e quais dependem do cliente ou da distribuidora.' }]
  },
  {
    slug: 'instalacao-de-cameras', name: 'Instalação de câmeras', title: 'Orçamento para instalação de câmeras de segurança',
    description: 'Detalhe pontos, câmeras, gravador, armazenamento, cabeamento, configuração, acesso remoto, testes e Pix.',
    promise: 'Modelo preparado para CFTV residencial e de pequenos negócios.',
    preset: { occupation: 'instalador de câmeras de segurança', items: [{ nome: 'Vistoria e definição dos pontos' }, { nome: 'Câmeras, gravador e armazenamento' }, { nome: 'Cabeamento, instalação e configuração' }], observacoes: 'Informe quantidade, tecnologia, resolução, retenção e condições de rede e energia.\nObra civil e adequações elétricas somente quando descritas.\nUso das imagens deve observar privacidade e regras aplicáveis.' },
    checklist: ['Pontos e campo de visão', 'Equipamentos e retenção', 'Rede, energia e acesso remoto'],
    example: { client: 'Cliente: Mercado Bom Dia — exemplo fictício', items: [{ description: 'Projeto dos pontos', detail: 'Vistoria e posicionamento de 6 câmeras', value: 'R$ 350,00' }, { description: 'Equipamentos', detail: '6 câmeras, gravador, HD e fontes', value: 'R$ 3.280,00' }, { description: 'Instalação', detail: 'Cabeamento, configuração, aplicativo e testes', value: 'R$ 1.870,00' }], total: 'R$ 5.500,00', terms: ['Prazo: 3 dias úteis', 'Internet fornecida pelo cliente', '40% de entrada via Pix'] },
    sections: [{ title: 'Imagem e armazenamento', paragraphs: ['Defina tecnologia, resolução, visão noturna, campo de visão e período estimado de retenção.', 'Explique o que depende de internet, aplicativo, conta do fabricante ou assinatura.'] }, { title: 'Privacidade e segurança de acesso', paragraphs: ['Posicionamento e uso das imagens devem respeitar privacidade e regras aplicáveis ao local.', 'Credenciais devem ser entregues com orientação para troca de senha e controle de acesso.'] }],
    faqs: [{ q: 'Quantos dias ficam gravados?', a: 'Depende de câmeras, resolução, taxa de gravação e capacidade do disco; apresente uma estimativa com essas premissas.' }, { q: 'Acesso pelo celular está incluso?', a: 'Declare configuração, dependência de internet e eventuais serviços de terceiros.' }]
  },
  {
    slug: 'instalacao-de-piso', name: 'Instalação de piso', title: 'Orçamento para instalação de piso por ambiente',
    description: 'Calcule retirada, preparação, metragem, instalação, rodapés, recortes, materiais, prazo e Pix por etapa.',
    promise: 'Modelo preparado para piso laminado, vinílico, cerâmico e outros sistemas especificados.',
    preset: { occupation: 'instalador de piso', items: [{ nome: 'Retirada e preparação da base' }, { nome: 'Instalação do piso' }, { nome: 'Rodapés, perfis, recortes e limpeza' }], observacoes: 'Informe ambientes, área, tipo de piso e condição da base.\nRegularização, impermeabilização e retirada devem ser descritas separadamente.\nEntrada para materiais e saldo via Pix após conferência.' },
    checklist: ['Área e tipo de piso', 'Base e retirada', 'Rodapés, recortes e perdas'],
    example: { client: 'Cliente: Escritório Pinheiros — exemplo fictício', items: [{ description: 'Preparação', detail: 'Correções localizadas e limpeza de 54 m²', value: 'R$ 810,00' }, { description: 'Instalação', detail: 'Piso vinílico colado em 54 m²', value: 'R$ 2.700,00' }, { description: 'Acabamento', detail: '48 m de rodapé, perfis e recortes', value: 'R$ 1.190,00' }], total: 'R$ 4.700,00', terms: ['Prazo: 5 dias úteis', 'Piso fornecido pelo cliente', '30% de entrada via Pix'] },
    sections: [{ title: 'A base faz parte do preço', paragraphs: ['Planicidade, umidade, resíduos e revestimento existente influenciam o sistema de instalação.', 'Separe retirada, descarte, regularização e instalação para tornar o orçamento comparável.'] }, { title: 'Perdas e acabamentos', paragraphs: ['Considere paginação, recortes e percentual de perda apropriado ao ambiente e produto.', 'Rodapés, soleiras, perfis, portas e movimentação de móveis devem aparecer no escopo.'] }],
    faqs: [{ q: 'Como calcular a quantidade de piso?', a: 'Meça a área e acrescente perda compatível com paginação, recortes e orientação do fabricante.' }, { q: 'Regularização está incluída?', a: 'Somente se descrita após avaliar a base; correções extensas devem ser orçadas separadamente.' }]
  }
];
